### PR TITLE
Import from Bazel

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by fmeum** [comment]
@meteorcloudy After the merge of https://github.com/bazelbuild/bazel/pull/23331, I could also move over the runfiles library.

**Comment by fmeum** [comment]
@comius The tests are passing on Linux and macOS, Windows needs https://github.com/bazelbuild/bazel/pull/23873.

**Review by meteorcloudy — APPROVED** [review]
Thanks!!

**Comment by fmeum** [comment]
@meteorcloudy Could you give me access to the repo? I can't merge PRs.

**Comment by Wyverald** [comment]
@fmeum Just added you to maintainers, please check again!

**Pull request merged**
