### PR TITLE
Rename to rules_shell

### PR DESCRIPTION
**Pull request by meteorcloudy**
Context https://github.com/bazelbuild/bazel/pull/23660

### CODE REVIEW

**Comment by fmeum** [comment]
I think that it could be confusing if `sh_binary` lives in `rules_shell`, not `rules_sh`. But I guess renaming the rule itself to `shell_binary` (which would be more accurate, it even defaults to `bash`) would be even more annoying?

**Comment by fmeum** [comment]
Nvm, I just noticed that rules_python and rules_py are precedent for this and everyone seems to be doing okay. I will send a PR.

**Comment by meteorcloudy** [comment]
Yeah, and we also have https://bazel.build/reference/be/shell

**Pull request merged**
